on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.22.x", "1.23.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test v4 core
        run: cd v4 && go test ./paginate/... -count=1
      - name: Test v4 gormpaginate
        run: cd v4/gormpaginate && go test ./... -count=1
